# Generated by Django 4.2.4 on 2023-09-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
